"""Add is_active to campus_products

Revision ID: 0514c358cb20
Revises: 49b6dc271363
Create Date: 2025-11-24 08:18:48.306505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0514c358cb20'
down_revision = '49b6dc271363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_products', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
