"""Create campus_products table

Revision ID: 1f01a78e625a
Revises: 2ef6a6ea8952
Create Date: 2025-10-21 17:15:15.561786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f01a78e625a'
down_revision = '2ef6a6ea8952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('campus_quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(10, 2), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_campus',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'campus_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_campus_id_fkey'), type_='foreignkey')
        batch_op.drop_column('campus_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('products_campus_id_fkey'), 'campuses', ['campus_id'], ['id'])

    op.drop_table('product_campus')
    op.drop_table('campus_products')
    # ### end Alembic commands ###
