"""Add subcategory to Product

Revision ID: 27db4b0abce5
Revises: ed3e99384e45
Create Date: 2025-10-19 20:27:49.279902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27db4b0abce5'
down_revision = 'ed3e99384e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###
