"""Add product table

Revision ID: 297833b5015a
Revises: 91104e407afe
Create Date: 2025-10-09 22:43:02.320099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297833b5015a'
down_revision = '91104e407afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('image_file', sa.String(length=255), nullable=True),
    sa.Column('image_gallery', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
