"""Add sub_category_id to Product model

Revision ID: 4e0d4d4f2ba8
Revises: 5ac2b492e200
Create Date: 2025-10-19 22:17:58.935131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0d4d4f2ba8'
down_revision = '5ac2b492e200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
         batch_op.add_column(sa.Column('sub_category_id', sa.Integer(), nullable=True))
         batch_op.create_foreign_key(None, 'sub_category', ['sub_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sub_category_id')

    # ### end Alembic commands ###
