"""Add start_date and end_date to users

Revision ID: 532e20e443b9
Revises: e61ba641e1d2
Create Date: 2025-11-14 21:38:29.386122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532e20e443b9'
down_revision = 'e61ba641e1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_campus')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    op.create_table('product_campus',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campus_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('product_campus_campus_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_campus_product_id_fkey')),
    sa.PrimaryKeyConstraint('product_id', 'campus_id', name=op.f('product_campus_pkey'))
    )
    # ### end Alembic commands ###
