"""Add campus_id to products

Revision ID: 61f62a2cc190
Revises: e40fe192f62b
Create Date: 2025-10-17 01:24:39.359555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f62a2cc190'
down_revision = 'e40fe192f62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'campuses', ['campus_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campus_id')

    # ### end Alembic commands ###
