"""Add campus_product_id to CartItem

Revision ID: 8771d5765973
Revises: b26caa69db51
Create Date: 2025-10-22 01:16:32.558976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8771d5765973'
down_revision = 'b26caa69db51'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        # 1. Add as nullable first
        batch_op.add_column(sa.Column('campus_product_id', sa.Integer(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('cart_item_product_id_fkey'), type_='foreignkey')

    # 2. Populate campus_product_id for existing rows (set to a valid campus_product_id, e.g., 1)
    op.execute('UPDATE cart_item SET campus_product_id = 1 WHERE campus_product_id IS NULL')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        # 3. Set NOT NULL and add FK
        batch_op.alter_column('campus_product_id', nullable=False)
        batch_op.create_foreign_key(None, 'campus_products', ['campus_product_id'], ['id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_item_product_id_fkey'), 'products', ['product_id'], ['id'])
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('campus_product_id')

    # ### end Alembic commands ###
