"""Add price to OrderItem

Revision ID: 929d4f5beb6d
Revises: 8771d5765973
Create Date: 2025-10-22 01:53:01.833310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929d4f5beb6d'
down_revision = '8771d5765973'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        # 1. Add as nullable with default
        batch_op.add_column(sa.Column('price', sa.Numeric(10, 2), nullable=True, server_default='0.00'))

    # 2. (Optional) Set a different value for existing rows if needed
    # op.execute('UPDATE order_items SET price = <some_value> WHERE price IS NULL')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        # 3. Set NOT NULL and remove default
        batch_op.alter_column('price', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
