"""updated user model with better clearance handlign and added class methods

Revision ID: ba6fecf21894
Revises: 9ed32e4e2c89
Create Date: 2025-10-10 22:53:32.996659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6fecf21894'
down_revision = '9ed32e4e2c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clearance_level', sa.Integer(), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('clearance_level')

    # ### end Alembic commands ###
