"""Make sub_category_id NOT NULL

Revision ID: e3df5eda36d6
Revises: 4e0d4d4f2ba8
Create Date: 2025-10-19 22:25:26.692264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3df5eda36d6'
down_revision = '4e0d4d4f2ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('sub_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('sub_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
