"""Remove image_url column from Product

Revision ID: e40fe192f62b
Revises: 997036ff1704
Create Date: 2025-10-17 00:59:59.962343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40fe192f62b'
down_revision = '997036ff1704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
