"""Add spa_quantity to CampusProduct

Revision ID: e61ba641e1d2
Revises: 929d4f5beb6d
Create Date: 2025-10-23 22:39:53.227576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61ba641e1d2'
down_revision = '929d4f5beb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spa_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_products', schema=None) as batch_op:
        batch_op.drop_column('spa_quantity')

    # ### end Alembic commands ###
